sudo: required
language: generic 
services:
  - docker

before_install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t hlucco/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true USERNAME/react-test npm test

after_success:
  - docker build -t hlucco/multi-client ./client
  - docker build -t hlucco/multi-nginx ./nginx
  - docker build -t hlucco/multi-server ./server
  - docker build -t hlucco/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push hucco/multi-client
  - docker push hucco/multi-nginx
  - docker push hucco/multi-server
  - docker push hucco/multi-worker

