sudo: required
language: generic 
services:
  - docker

before_install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t hlucco/react-test -f ./client/Dockerfile.dev ./client

script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

after_success:
  - docker build -t hlucco/multi-client ./client
  - docker build -t hlucco/multi-nginx ./nginx
  - docker build -t hlucco/multi-server ./server
  - docker build -t hlucco/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push hlucco/multi-client
  - docker push hlucco/multi-nginx
  - docker push hlucco/multi-server
  - docker push hlucco/multi-worker

